package parkandrest.parkingmanagement.api.businessexception

enum class BusinessExceptionCode {
    PARKING_NOT_EXISTS,
    PARKING_SPACE_UNAVAILABLE,
    PARKING_SPACE_NOT_EXISTS,
    NO_SUCH_VEHICLE_PARKED,
    NO_SUCH_TARIFF,
    NO_TARIFF_PRESENT,
    NO_SUCH_ORDER,
    TARIFFICATION_RULE_IS_MISSING,
    CURRENCY_MISMATCH,
    DIFFERENT_PARKING_ON_TARIFFS,
    DIFFERENT_TARIFFS_TYPES,
    INVALID_FORMULA
}